version: '3.9'

services:
  database:
    image: postgres
    container_name: database_desafio
    restart: always
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=desafio
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
